{
    "name": "Account Treasury",
    "version": "1.0",
    "category": "Accounting",
    "summary": "Account Treasury",
    "author": "Mahmoud Abdelaziz",
    'license': 'LGPL-3',
    "depends": ['efcbc_custom_account', 'account_audit', 'efcbc_report_layout'],
    "data": [
        "security/ir.model.access.csv",
        "views/account_payment.xml",
        "views/account_journal.xml",
        "views/payment_permission.xml",
        "wizards/account_treasury_report_wizard.xml",
        "report/draft_payment_permission_report.xml",
    ],
    "license": "AGPL-3",
    "installable": True,
    "auto_install": False,
}
